FUTURES_TRADING_ASSET = 'USDT'
SYMBOL = "XRPUSDT"
LEVERAGE = 1
MAX_POSITION_RATIO = 5 # % 전체자산 기준 최대 포지션 보유 가능 비율
MAX_RISK_RATIO = 1 # 0.25% ~ 1% 전체자산 기준 최대 손실 허용 비율
RISK_REWARD_RAITO = 2.0 # 손익비

# KLINE_INTERVAL
KLINE_INTERVAL = '5m'
KLINE_INTERVAL2 = '1d'

# DISCORD
DISCORD_WEBHOOK_URL = 'https://discord.com/api/webhooks/1375453664885473341/l9ASZS3clm_RTXMvq7kT2D3_wMC3J3uMeUwbQB0w54uBqu8zIxpYLvYCdoL2iibfvi6n'

### ENABLES ###
ENABLE_ORDER = False

MINIMUM_REQUIRED_RATIO = 62.5 # 모멘텀 캔들의 몸통 비율
