NO_DATA_TIMEOUT = 60 # # 데이터 수신이 없을 경우 연결 끊김으로 간주하는 시간 (초)
MAX_RECONNECT_ATTEMPTS = 10  # 최대 재연결 시도 횟수
BACKOFF_FACTOR = 2           # 지수 백오프에 사용될 계수
INITIAL_RECONNECT_DELAY = 1  # 초기 재연결 대기 시간 (초)
MAX_RETRY_DELAY = 60
MAX_RETRIES = 3 # 최대 재시도 횟수
RETRY_DELAY_SECONDS = 5 # 기본 재시도 지연 시간 (초)
MONITOR_INTERVAL_SECONDS = 1
MAX_WORKER_THREADS = 4 # 핸들러를 처리할 워커 스레드의 최대 개수 ex) 4 or 8
KLINE_LIMIT = 500 # get_klines() 호출 시 기본으로 가져올 캔들 개수
MAX_WAITING_SECONDS = 10
VALID_KLINES_LIMIT_MAX = 1000
CIRCUIT_BREAKER_MAX_FAILURES = 3 # 연속 실패 허용 횟수
CIRCUIT_BREAKER_TIMEOUT_SECONDS = 30 # 서킷 브레이커 열림 상태 유지 시간
ORDER_PLACEMENT_RETRY_DELAY = 5 # 주문 실패 시 재시도 대기 시간 (초)
